version: "3"
services:
  web:
    build:
      context: ..
      dockerfile: build/Dockerfile
      args:
        MONGO_CS: mongodb://mongo:27017
    ports:
      - "8080:8080"
  mongo:
    image: "mongo:4"
