language: go

branches:
  only:
  - master

services:
  - mongodb

before_install:
  - go get -t -u -v ./...

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
  - curl --location --remote-name --silent https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
  - chmod -c u+x wait-for-it.sh

before_script:
  - ./wait-for-it.sh --host=localhost --port=27017
  - mongo localhost:27017/test --eval 'db.runCommand("ping").ok'

script:
  - golangci-lint run --enable-all
  - go test --count=100 --covermode=atomic --coverprofile=coverage.txt --race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
