language: go

os: linux
arch: amd64
dist: bionic

go:
  - 1.x
  - main

env:
  - GO111MODULE=on

branches:
  only:
    - main

services:
  - mongodb

before_script:
  - until (echo > /dev/tcp/localhost/27017) &> /dev/null; do sleep 1; done
  - mongo localhost:27017/test --eval 'db.runCommand("ping").ok'

script:
  - go build ./...
  - go test --count=100 --covermode=atomic --coverprofile=coverage.txt --race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
