language: go

os: linux
arch: amd64
dist: bionic

go:
  - 1.x
  - master

env:
  - GO111MODULE=on

branches:
  only:
    - master

services:
  - mongodb

install:
  - curl --fail --location https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.19.1

before_script:
  - until (echo > /dev/tcp/localhost/27017) &> /dev/null; do sleep 1; done
  - mongo localhost:27017/test --eval 'db.runCommand("ping").ok'

script:
  - golangci-lint run
  - go build ./...
  - go test --count=100 --covermode=atomic --coverprofile=coverage.txt --race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
