language: go

branches:
  only:
  - master

services:
  - mongodb

before_install:
  - go get -t -u -v ./...

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

# todo:
# - https://github.com/vishnubob/wait-for-it
# - https://packages.debian.org/stretch/wait-for-it
before_script:
  - sleep 15
  - mongo localhost:27017/test --eval 'db.runCommand("ping").ok'

script:
  - golangci-lint run --enable-all
  - go test --count=100 --covermode=atomic --coverprofile=coverage.txt --race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
